// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: class.proto

#include "class.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_class_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_class_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_FullName;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_class_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Student;
}  // namespace protobuf_class_2eproto
namespace foo {
namespace bar {
class FullNameDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FullName>
      _instance;
} _FullName_default_instance_;
class StudentDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Student>
      _instance;
} _Student_default_instance_;
class StudentsGroupDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StudentsGroup>
      _instance;
} _StudentsGroup_default_instance_;
}  // namespace bar
}  // namespace foo
namespace protobuf_class_2eproto {
static void InitDefaultsFullName() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::foo::bar::_FullName_default_instance_;
    new (ptr) ::foo::bar::FullName();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::foo::bar::FullName::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_FullName =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsFullName}, {}};

static void InitDefaultsStudent() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::foo::bar::_Student_default_instance_;
    new (ptr) ::foo::bar::Student();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::foo::bar::Student::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Student =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsStudent}, {
      &protobuf_class_2eproto::scc_info_FullName.base,}};

static void InitDefaultsStudentsGroup() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::foo::bar::_StudentsGroup_default_instance_;
    new (ptr) ::foo::bar::StudentsGroup();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::foo::bar::StudentsGroup::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_StudentsGroup =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsStudentsGroup}, {
      &protobuf_class_2eproto::scc_info_Student.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_FullName.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Student.base);
  ::google::protobuf::internal::InitSCC(&scc_info_StudentsGroup.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foo::bar::FullName, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foo::bar::FullName, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foo::bar::FullName, surname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foo::bar::FullName, patronimic_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foo::bar::Student, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foo::bar::Student, full_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foo::bar::Student, grades_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foo::bar::Student, gpa_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foo::bar::StudentsGroup, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foo::bar::StudentsGroup, student_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::foo::bar::FullName)},
  { 8, -1, sizeof(::foo::bar::Student)},
  { 16, -1, sizeof(::foo::bar::StudentsGroup)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::foo::bar::_FullName_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::foo::bar::_Student_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::foo::bar::_StudentsGroup_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "class.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013class.proto\022\007foo.bar\"=\n\010FullName\022\014\n\004na"
      "me\030\001 \001(\t\022\017\n\007surname\030\002 \001(\t\022\022\n\npatronimic\030"
      "\003 \001(\t\"L\n\007Student\022$\n\tfull_name\030\001 \001(\0132\021.fo"
      "o.bar.FullName\022\016\n\006grades\030\002 \003(\005\022\013\n\003GPA\030\003 "
      "\001(\001\"2\n\rStudentsGroup\022!\n\007student\030\001 \003(\0132\020."
      "foo.bar.Studentb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 223);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "class.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_class_2eproto
namespace foo {
namespace bar {

// ===================================================================

void FullName::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FullName::kNameFieldNumber;
const int FullName::kSurnameFieldNumber;
const int FullName::kPatronimicFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FullName::FullName()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_class_2eproto::scc_info_FullName.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:foo.bar.FullName)
}
FullName::FullName(const FullName& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  surname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.surname().size() > 0) {
    surname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.surname_);
  }
  patronimic_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.patronimic().size() > 0) {
    patronimic_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.patronimic_);
  }
  // @@protoc_insertion_point(copy_constructor:foo.bar.FullName)
}

void FullName::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  surname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  patronimic_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

FullName::~FullName() {
  // @@protoc_insertion_point(destructor:foo.bar.FullName)
  SharedDtor();
}

void FullName::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  surname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  patronimic_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void FullName::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* FullName::descriptor() {
  ::protobuf_class_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_class_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FullName& FullName::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_class_2eproto::scc_info_FullName.base);
  return *internal_default_instance();
}


void FullName::Clear() {
// @@protoc_insertion_point(message_clear_start:foo.bar.FullName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  surname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  patronimic_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool FullName::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:foo.bar.FullName)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "foo.bar.FullName.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string surname = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_surname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->surname().data(), static_cast<int>(this->surname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "foo.bar.FullName.surname"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string patronimic = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_patronimic()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->patronimic().data(), static_cast<int>(this->patronimic().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "foo.bar.FullName.patronimic"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:foo.bar.FullName)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:foo.bar.FullName)
  return false;
#undef DO_
}

void FullName::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:foo.bar.FullName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "foo.bar.FullName.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // string surname = 2;
  if (this->surname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->surname().data(), static_cast<int>(this->surname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "foo.bar.FullName.surname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->surname(), output);
  }

  // string patronimic = 3;
  if (this->patronimic().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->patronimic().data(), static_cast<int>(this->patronimic().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "foo.bar.FullName.patronimic");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->patronimic(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:foo.bar.FullName)
}

::google::protobuf::uint8* FullName::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:foo.bar.FullName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "foo.bar.FullName.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // string surname = 2;
  if (this->surname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->surname().data(), static_cast<int>(this->surname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "foo.bar.FullName.surname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->surname(), target);
  }

  // string patronimic = 3;
  if (this->patronimic().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->patronimic().data(), static_cast<int>(this->patronimic().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "foo.bar.FullName.patronimic");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->patronimic(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foo.bar.FullName)
  return target;
}

size_t FullName::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foo.bar.FullName)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string surname = 2;
  if (this->surname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->surname());
  }

  // string patronimic = 3;
  if (this->patronimic().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->patronimic());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FullName::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:foo.bar.FullName)
  GOOGLE_DCHECK_NE(&from, this);
  const FullName* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FullName>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:foo.bar.FullName)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:foo.bar.FullName)
    MergeFrom(*source);
  }
}

void FullName::MergeFrom(const FullName& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:foo.bar.FullName)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.surname().size() > 0) {

    surname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.surname_);
  }
  if (from.patronimic().size() > 0) {

    patronimic_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.patronimic_);
  }
}

void FullName::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:foo.bar.FullName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FullName::CopyFrom(const FullName& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foo.bar.FullName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FullName::IsInitialized() const {
  return true;
}

void FullName::Swap(FullName* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FullName::InternalSwap(FullName* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  surname_.Swap(&other->surname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  patronimic_.Swap(&other->patronimic_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata FullName::GetMetadata() const {
  protobuf_class_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_class_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Student::InitAsDefaultInstance() {
  ::foo::bar::_Student_default_instance_._instance.get_mutable()->full_name_ = const_cast< ::foo::bar::FullName*>(
      ::foo::bar::FullName::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Student::kFullNameFieldNumber;
const int Student::kGradesFieldNumber;
const int Student::kGPAFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Student::Student()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_class_2eproto::scc_info_Student.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:foo.bar.Student)
}
Student::Student(const Student& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      grades_(from.grades_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_full_name()) {
    full_name_ = new ::foo::bar::FullName(*from.full_name_);
  } else {
    full_name_ = NULL;
  }
  gpa_ = from.gpa_;
  // @@protoc_insertion_point(copy_constructor:foo.bar.Student)
}

void Student::SharedCtor() {
  ::memset(&full_name_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&gpa_) -
      reinterpret_cast<char*>(&full_name_)) + sizeof(gpa_));
}

Student::~Student() {
  // @@protoc_insertion_point(destructor:foo.bar.Student)
  SharedDtor();
}

void Student::SharedDtor() {
  if (this != internal_default_instance()) delete full_name_;
}

void Student::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Student::descriptor() {
  ::protobuf_class_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_class_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Student& Student::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_class_2eproto::scc_info_Student.base);
  return *internal_default_instance();
}


void Student::Clear() {
// @@protoc_insertion_point(message_clear_start:foo.bar.Student)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  grades_.Clear();
  if (GetArenaNoVirtual() == NULL && full_name_ != NULL) {
    delete full_name_;
  }
  full_name_ = NULL;
  gpa_ = 0;
  _internal_metadata_.Clear();
}

bool Student::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:foo.bar.Student)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .foo.bar.FullName full_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_full_name()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 grades = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_grades())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 18u, input, this->mutable_grades())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double GPA = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &gpa_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:foo.bar.Student)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:foo.bar.Student)
  return false;
#undef DO_
}

void Student::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:foo.bar.Student)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .foo.bar.FullName full_name = 1;
  if (this->has_full_name()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_full_name(), output);
  }

  // repeated int32 grades = 2;
  if (this->grades_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _grades_cached_byte_size_));
  }
  for (int i = 0, n = this->grades_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->grades(i), output);
  }

  // double GPA = 3;
  if (this->gpa() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->gpa(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:foo.bar.Student)
}

::google::protobuf::uint8* Student::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:foo.bar.Student)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .foo.bar.FullName full_name = 1;
  if (this->has_full_name()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_full_name(), deterministic, target);
  }

  // repeated int32 grades = 2;
  if (this->grades_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _grades_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->grades_, target);
  }

  // double GPA = 3;
  if (this->gpa() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->gpa(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foo.bar.Student)
  return target;
}

size_t Student::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foo.bar.Student)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated int32 grades = 2;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->grades_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _grades_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // .foo.bar.FullName full_name = 1;
  if (this->has_full_name()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *full_name_);
  }

  // double GPA = 3;
  if (this->gpa() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Student::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:foo.bar.Student)
  GOOGLE_DCHECK_NE(&from, this);
  const Student* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Student>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:foo.bar.Student)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:foo.bar.Student)
    MergeFrom(*source);
  }
}

void Student::MergeFrom(const Student& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:foo.bar.Student)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  grades_.MergeFrom(from.grades_);
  if (from.has_full_name()) {
    mutable_full_name()->::foo::bar::FullName::MergeFrom(from.full_name());
  }
  if (from.gpa() != 0) {
    set_gpa(from.gpa());
  }
}

void Student::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:foo.bar.Student)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Student::CopyFrom(const Student& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foo.bar.Student)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Student::IsInitialized() const {
  return true;
}

void Student::Swap(Student* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Student::InternalSwap(Student* other) {
  using std::swap;
  grades_.InternalSwap(&other->grades_);
  swap(full_name_, other->full_name_);
  swap(gpa_, other->gpa_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Student::GetMetadata() const {
  protobuf_class_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_class_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void StudentsGroup::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StudentsGroup::kStudentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StudentsGroup::StudentsGroup()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_class_2eproto::scc_info_StudentsGroup.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:foo.bar.StudentsGroup)
}
StudentsGroup::StudentsGroup(const StudentsGroup& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      student_(from.student_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:foo.bar.StudentsGroup)
}

void StudentsGroup::SharedCtor() {
}

StudentsGroup::~StudentsGroup() {
  // @@protoc_insertion_point(destructor:foo.bar.StudentsGroup)
  SharedDtor();
}

void StudentsGroup::SharedDtor() {
}

void StudentsGroup::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* StudentsGroup::descriptor() {
  ::protobuf_class_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_class_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StudentsGroup& StudentsGroup::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_class_2eproto::scc_info_StudentsGroup.base);
  return *internal_default_instance();
}


void StudentsGroup::Clear() {
// @@protoc_insertion_point(message_clear_start:foo.bar.StudentsGroup)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  student_.Clear();
  _internal_metadata_.Clear();
}

bool StudentsGroup::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:foo.bar.StudentsGroup)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .foo.bar.Student student = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_student()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:foo.bar.StudentsGroup)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:foo.bar.StudentsGroup)
  return false;
#undef DO_
}

void StudentsGroup::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:foo.bar.StudentsGroup)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .foo.bar.Student student = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->student_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->student(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:foo.bar.StudentsGroup)
}

::google::protobuf::uint8* StudentsGroup::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:foo.bar.StudentsGroup)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .foo.bar.Student student = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->student_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->student(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foo.bar.StudentsGroup)
  return target;
}

size_t StudentsGroup::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foo.bar.StudentsGroup)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .foo.bar.Student student = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->student_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->student(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StudentsGroup::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:foo.bar.StudentsGroup)
  GOOGLE_DCHECK_NE(&from, this);
  const StudentsGroup* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StudentsGroup>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:foo.bar.StudentsGroup)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:foo.bar.StudentsGroup)
    MergeFrom(*source);
  }
}

void StudentsGroup::MergeFrom(const StudentsGroup& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:foo.bar.StudentsGroup)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  student_.MergeFrom(from.student_);
}

void StudentsGroup::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:foo.bar.StudentsGroup)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StudentsGroup::CopyFrom(const StudentsGroup& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foo.bar.StudentsGroup)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StudentsGroup::IsInitialized() const {
  return true;
}

void StudentsGroup::Swap(StudentsGroup* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StudentsGroup::InternalSwap(StudentsGroup* other) {
  using std::swap;
  CastToBase(&student_)->InternalSwap(CastToBase(&other->student_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata StudentsGroup::GetMetadata() const {
  protobuf_class_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_class_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace bar
}  // namespace foo
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::foo::bar::FullName* Arena::CreateMaybeMessage< ::foo::bar::FullName >(Arena* arena) {
  return Arena::CreateInternal< ::foo::bar::FullName >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::foo::bar::Student* Arena::CreateMaybeMessage< ::foo::bar::Student >(Arena* arena) {
  return Arena::CreateInternal< ::foo::bar::Student >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::foo::bar::StudentsGroup* Arena::CreateMaybeMessage< ::foo::bar::StudentsGroup >(Arena* arena) {
  return Arena::CreateInternal< ::foo::bar::StudentsGroup >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
